### ISSUE TITLE
Cần giúp hiệu ứng khi auto typing text!

### ISSUE THREAD

**Issue by trungkien89** [phuongla/react-native-auto-typing-text#1]
Có cách nào thay đổi cái hiệu ứng text kia không bro? 
Ví dụ như mình có 1 đoạn text dài trên title của 1 list view. mình muốn nó chạy dần dần từ phải qua trái có được không?
Cám ơn vì đã làm cái auto typing text này!

**Comment by ngothanhtai** [comment]
Bạn mô tả là chạy từ phải qua trái như thế nào chi tiết được không? Vì nó có rất nhiều cách.

**Comment by trungkien89** [comment]
ý mình là thế này : Mình có 1 component để hiển thị tin tức . nó có cái tiêu đề và phần mô tả nhé. 
cái tiêu đề mình muốn khi màn hình dược load ra thì cái tiêu đề này chạy từ phía phải qua . ví dụ tiêu đề là " ĐÂY LÀ TIÊU ĐỀ "
thì lúc load nó chạy thế này
 ..............ĐÂY
........ĐÂY LÀ
...ĐÂY LÀ TIÊU
ĐÂY LÀ TIÊU ĐỀ . 
rồi khi cái hiệu ứng này chạy xong thì có props nào cho nó replay lại được không?

**Comment by ngothanhtai** [comment]
Bạn set style `textAlign: 'right'` là được nhé!
Ví dụ:
```
<AutoTypingText
  text={`có căn nhà nằm nghe nắng mưa`}
  charMovingTime={80}
  delay={0}
  style={{
    position: 'absolute',
    width: width - 40,
    fontSize: 30,
    color: 'rgba(255,255,255,0.7)',
    backgroundColor: 'rgba(0,0,0,0)',
    margin: 20,
    top: 240,
    textAlign: 'right'
  }}
  onComplete={() => { console.log('done'); }}
/>
```

Còn về phần replay thì mình sẽ thêm sau nhé!

**Comment by ngothanhtai** [comment]
Mình đã add todos cho version 1.0.5 rồi nhé
https://github.com/phuongla/react-native-auto-typing-text/projects/1
